### ISSUE TITLE
Create HDF5 scripts and documentation

### ISSUE THREAD

**Issue by JimHokanson** [openworm/OpenWorm#146]
Currently the movement validation data we are working with is Matlab's version of HDF5 data. We currently have data that reads from these files, although we also need to write these files. In general extra documentation would help.

Reading example:
https://gist.github.com/JimHokanson/6420348

Incomplete documentation at (with respect to Matlab strings):
https://github.com/JimHokanson/openworm_docs/blob/master/Movement/Data/MRC_HDF5.md

No writing examples currently, but this would be useful for issue #144 and #145.

The HDF5 specification is somewhat flexible in terms of how data are represented, which means that going to and from the format in Python isn't always super straightforward.

Completed code and documentation should go under:
https://github.com/JimHokanson/openworm_docs

in a folder /python/hdf5

Bonus points:
Make the written files Matlab compatible.

h5py why?
We are currently using h5py, due to limitations encountered with pytables, which I believe are addressed either in the gist that provides the read examples, or in issue #82 

That's not to say that h5py is the best way to go. Feel free to address this issue, however the main benefits of implementing this issue are:
- having writing examples
- having centralized documentation on dealing with this format

**Comment by MichaelCurrie** [comment]
This is superceded by the JSON-based tracker-commons format, WCON.  (https://github.com/openworm/tracker-commons/)

[Issue 169](https://github.com/openworm/open-worm-analysis-toolbox/issues/169) in the open-worm-analysis-toolbox repo (formerly movement_validation) talks about subclassing the WCON format for the purposes Jim describes.  So this issue here is complete/moot.
