### ISSUE TITLE
Combine docker file from openworm/tests with the master simulation stack docker file in this repo

### ISSUE THREAD

**Issue by slarson** [openworm/OpenWorm#282]
This could be done by extending the master docker image, or by directly combining them.  What do folks think are the best way to do this?

We talked about doing this with Docker compose but this would end up being significantly complex.

**Comment by rgerkin** [comment]
Option 1: Extending the master Docker image.  I would need to add a Jupyter notebook server, and more python packages than it currently has.  

Option 2: Making the master Docker image start from a richer source than "Ubuntu 16.04", e.g. one of Jupyter's Docker Stacks images [here](https://github.com/jupyter/docker-stacks).  The advantage is that the Jupyter team handles most of the bug patching of most of the stack, as well as python package compatibility.  There is enough Python going on in OpenWorm that I think having a Python-aiming base image like scipy-notebook or datascience-notebook from the link above.  We can still add any other dependencies we need just like we do in the current master image, except we would need fewer of them because many are already installed.  This also means it should build faster (given that we trust the base image from Jupyter).  

You can probably tell that I prefer option 2.

**Comment by pgleeson** [comment]
Looking into this a bit (trying option 2)... I guess using Python 3 is a deal breaker for you @rgerkin?

**Comment by slarson** [comment]
Just wanted to point to this effort to combine the main docker image with a jupyter notebook here: https://github.com/slarson/OpenWorm/blob/jupyter-notebook/notebook/Dockerfile

**Comment by rgerkin** [comment]
@slarson That looks like a good approach.  I'll look into extending from that one.  

@pgleeson I thought we were a Python 3 shop?  :) 
I always write for Python 3 but for sciunit/neuronunit I've kept everything Python 2.7 compatible as well... so far.

**Comment by pgleeson** [comment]
Closing as https://github.com/openworm/tests hasn't been updated in a while. Will open a new issue specific for testing Docker container with JupyterLab
