### ISSUE TITLE
Docker : xhost command not found and no such container openworm

### ISSUE THREAD

**Issue by moanra** [openworm/OpenWorm#295]
![docker](https://user-images.githubusercontent.com/48910563/58965025-2702ce80-87b0-11e9-8006-261428d8d68e.PNG)

**Comment by suzil** [comment]
It looks like you are on Windows, so you need to have an X server running in order to access the xhost command. I don't know much about Windows, but you could try to use [Cygwin](https://x.cygwin.com/).

> Cygwin/X consists of an X server, X libraries, and nearly all of the standard X clients, such as xterm, **xhost**, xdpyinfo, xclock, xeyes, etc. Many more X programs are also packaged for Cygwin. See also the features and screenshots pages.

That said,
> Currently Windows is not supported (see https://github.com/openworm/OpenWorm/issues/263); you will need Mac OS or Linux (or a virtual environment on Windows that runs either of those).
([source](https://github.com/openworm/OpenWorm/blob/ed5b2c664b3e43c4fc798a71364c35280cddf95a/README.md#quickstart))

**Comment by pgleeson** [comment]
There have been some helper scripts for Windows added recently (build.cmd and run.cmd, see https://github.com/openworm/OpenWorm/pull/294)  in the development branch (https://github.com/openworm/OpenWorm/tree/development) and these work fine for running the simulation & generating the movie. Could some others test?

**Comment by pgleeson** [comment]
Fixed by adding windows specific scripts
